// { letter: '', word: '', definition: '' },

const listAZ = [
    { letter: 'A', word: 'ANTERIORE', definition: 'Altro termine per definire il "futuro composto"' },
    { letter: 'B', word: 'BOMBOLE', definition: 'Fungono da riserve di aria per i sub' },
    { letter: 'C', word: 'CUMINO', definition: 'Una delle spezie del curry' },
    { letter: 'D', word: 'DUECENTO', definition: 'Per gli antichi romani è CC' },
    { letter: 'E', word: 'ESTORIL', definition: 'Località portoghese che ospitava il motomondiale' },
    { letter: 'F', word: 'FONDOTINTA', definition: 'Copre le imperfezioni del viso' },
    { letter: 'G', word: 'GUACCERO', definition: 'Bianca, attrice e conduttrice italiana' },
    { letter: 'H', word: 'HERBST', definition: 'Autunno in tedesco' },
    { letter: 'I', word: 'IRA', definition: 'Un vizio capitale' },
    { letter: 'L', word: 'LIBERO', definition: 'Ruolo calcistico ricoperto da Franco Baresi' },
    { letter: 'M', word: 'MELE', definition: 'Crescono sugli alberi di "Malus Domestica"' },
    { letter: 'N', word: 'NUBIANI', definition: 'Antico popolo dell\'Africa Nord-Orientale' },
    { letter: 'O', word: 'ODEON', definition: 'Piccolo teatro coperto dell\'Antica Grecia' },
    { letter: 'P', word: 'PORTHOS', definition: 'Uno dei tre moschettieri' },
    { letter: 'Q', word: 'QWERTY', definition: 'La tastiera standard inglese' },
    { letter: 'R', word: 'REGINELLE', definition: 'Biscotti palermitani ricoperti di sesamo' },
    { letter: 'S', word: 'STUART', definition: 'Storica famiglia reale scozzese' },
    { letter: 'T', word: 'TANATOFOBICO', definition: 'Teme ossessivamente la morte' },
    { letter: 'U', word: 'URBANISTICA', definition: 'La scienza che studia città' },
    { letter: 'V', word: 'VOGLIA', definition: 'Manca al pigro' },
    { letter: 'Z', word: 'ZAMBIA', definition: 'La nazione africana con Lusaka' },
];

const listZA = [
    { letter: 'Z', word: 'ZIBIBBO', definition: 'Un vino dolce' },
    { letter: 'V', word: 'VOLGA', definition: 'Il più lungo fiume europeo' },
    { letter: 'U', word: 'UNSPUNNEN', definition: 'La sua pietra si lancia in un tradizionale gioco svizzero' },
    { letter: 'T', word: 'TORBA', definition: 'Giacimento di resti vegetali non decomposti' },
    { letter: 'S', word: 'SAETTA', definition: 'McQueen, protagonista di "Cars"' },
    { letter: 'R', word: 'RAGNI', definition: 'Nome comune degli araneidi' },
    { letter: 'Q', word: 'QUI', definition: 'Con Quo e Qua' },
    { letter: 'P', word: 'PINGU', definition: 'La più conosciuta opera di Otmar Gutmann' },
    { letter: 'O', word: 'OLIVIERO', definition: 'Il nome del fotografo Toscani' },
    { letter: 'N', word: 'NAVARRA', definition: 'Comunità autonoma del nord della Spagna' },
    { letter: 'M', word: 'MANIERE', definition: 'Quelle buone sono insegnate dal galateo' },
    { letter: 'L', word: 'LINGERIE', definition: 'Biancheria intima femminile' },
    { letter: 'I', word: 'INDEPENDIENTE', definition: 'Blasonato club calcistico Argentino' },
    { letter: 'H', word: 'HONKY', definition: 'Insieme a "tonk" è il nome di un genere musicale' },
    { letter: 'G', word: 'GAELICO', definition: 'Insieme all\'inglese, è la lingua nazionale dell\'Irlanda' },
    { letter: 'F', word: 'FORZA', definition: 'È misurata dallo Newton' },
    { letter: 'E', word: 'ERITREA', definition: 'Asmara è la sua capitale' },
    { letter: 'D', word: 'DEIMOS', definition: 'Un satellite del pianeta Marte' },
    { letter: 'C', word: 'CARLINO', definition: 'Cane di piccola taglia, originario della Cina' },
    { letter: 'B', word: 'BRACARONE', definition: 'Persona sciatta e trasandata' },
    { letter: 'A', word: 'ALASKA', definition: 'Lo stato americano con l\'aurora boreale' },
];